name: Documentation

env:
  DEPLOY_BRANCH_POSTFIX: docs # Configure the destination branch postfix (code on "main" branch will be built and pushed into "main-POSTFIX" branch)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  Doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          if[! -d ~/home/runner/work/NaniteRendereringRecreation/NaniteRendereringRecreation]
            echo "hi"
          fi
      - name: Running Doxygen
        uses: mattnotmitt/doxygen-action@1.9.5
        with:
          doxyfile-path: Doxyfile
          working-directory: /home/runner/work/NaniteRendereringRecreation/NaniteRendereringRecreation
          enable-latex: true
        # Synchronize & push BUILD directory to deployment branch
      - name: Moving docs to folder
        run: |
          mkdir DOCS
          echo ${{ env.GITHUB_WORKSPACE }}
          mv latex DOCS
      - name: Configure Git informations
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
      - name: Push Docs To Branch
        run: |
          GIT_BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
          DEPLOY_BRANCH=$GIT_BRANCH-$DEPLOY_BRANCH_POSTFIX
          GIT_COMMIT=$(git rev-parse --short HEAD)
          mkdir RELEASE_DOCS
          mv .git RELEASE_DOCS/.git
          cd RELEASE_DOCS
          echo "Checking out $DEPLOY_BRANCH"
          git checkout -b $DEPLOY_BRANCH
          git stash && git stash drop
          (git pull --depth 1 origin $DEPLOY_BRANCH --rebase -X theirs --allow-unrelated-histories) || (echo "Deployment branch synced")
          mv ./.git ../.git
          cd ..
          # Push build into the deployment branch
          echo "Pushing build $GIT_COMMIT to $DEPLOY_BRANCH"
          mv .git DOCS/.git
          cd DOCS
          git add -A
          git commit -m "Automated build $GIT_COMMIT"
          git push origin $DEPLOY_BRANCH
          cd ..
